`Attributes of arrays`: Determing the size, shape, memoory consumption, and data types of arrays.<br>
`Indexing of arrays`: Getting and setting the value of individual array elements<br>
`Slicing of arrays`: Getting and setting smaller subarrays within a larger array <br>
`Reshaping of arrays`: Getting the shape of a given array
`Joining and splitting of arrays`: Combining multiple arrays into one, and splitting one array into many


# NumPy Array Attributes


In [7]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size=6)
print(x1)


[5 0 3 3 7 9]


In [8]:
x2 = np.random.randint(10, size=(3, 4))
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [14]:
x3 = np.random.randint(10, size=(3, 4, 5))
print(x3)
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)
print("x3 dtype: ", x3.dtype)
print("x3 itemsize: ", x3.itemsize, "bytes")  # lists the size (in bytes) of each array element
print("x3 nbytes: ", x3.nbytes, "bytes")  # lists the total size(in bytes) of the array 
# nbytes = itemsize * size = 8 * 60 

[[[3 3 9 2 5]
  [2 3 5 7 2]
  [7 1 6 5 0]
  [0 3 1 9 9]]

 [[6 6 7 8 8]
  [7 0 8 6 8]
  [9 8 3 6 1]
  [7 4 9 2 0]]

 [[8 2 7 8 4]
  [4 1 7 6 9]
  [4 1 5 9 7]
  [1 3 5 7 3]]]
x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
x3 dtype:  int64
x3 itemsize:  8 bytes
x3 nbytes:  480 bytes


# Array Indexing: Accessing Single Elements

In [15]:
x1

array([5, 0, 3, 3, 7, 9])

In [16]:
x1[0]

5

In [17]:
x1[4]

7

In [18]:
x1[-1]  # To index from the end of the array, use negative indices:

9

In [19]:
x1[-2]

7

In [20]:
# In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [21]:
x2[0, 0]

3

In [22]:
x2[2, 0]

1

In [23]:
x2[2, -1]

7

In [25]:
x2[0, 0] = 666
x2

array([[666,   5,   2,   4],
       [  7,   6,   8,   8],
       [  1,   6,   7,   7]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. 
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. 
Don't be caught unaware by this behaviour!

In [26]:
x1[0] = 3.1415926
x1

array([3, 0, 3, 3, 7, 9])

# Array Slicing: Accessing Subarrays

use way: `x[start:stop:step`

If any of these are unspecified, they default to the values `start=0`, `stop= size of dimension`, `step=1`.

## One-dimensional subarrays

In [29]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
x[:5]

array([0, 1, 2, 3, 4])

In [31]:
x[5:]

array([5, 6, 7, 8, 9])

In [32]:
x[4:7]

array([4, 5, 6])

In [33]:
x[::2]

array([0, 2, 4, 6, 8])

In [34]:
x[1::2]

array([1, 3, 5, 7, 9])

In [35]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [36]:
x[5::2]

array([5, 7, 9])

In [37]:
x[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
x[:1]

array([0])

In [40]:
x[::1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
x[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
x[1::]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
x[-1]

9

In [44]:
x[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Multi-dimensional subarrays



In [46]:
x2

array([[666,   5,   2,   4],
       [  7,   6,   8,   8],
       [  1,   6,   7,   7]])

In [47]:
x2[:2, :3]  # two rows, three columns

array([[666,   5,   2],
       [  7,   6,   8]])

In [48]:
x2[:3, ::2]  # all rows, every other column

array([[666,   2],
       [  7,   8],
       [  1,   7]])

In [49]:
x2[::-1, ::-1]

array([[  7,   7,   6,   1],
       [  8,   8,   6,   7],
       [  4,   2,   5, 666]])

### Accessing array rows and columns
`(:):`

In [50]:
print(x2[:, 0]) # first column of x2

[666   7   1]


In [51]:
print(x2[0, :]) # first row of x2

[666   5   2   4]


In [52]:
print(x2[0])  # equivalent to x2[0, :]

[666   5   2   4]


## Subarrays as no-copy views

One important-and extremely useful-thing to know about array slices is that they return **`views`**  rather than **`copies`** of the array data.

**This is one area in which NumPy array slicing differes from Python list slicing**
__in lists, slices will be copies.__

In [53]:
print(x2)

[[666   5   2   4]
 [  7   6   8   8]
 [  1   6   7   7]]


In [54]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[666   5]
 [  7   6]]


Now if we modify this subarray, the original array is changed! Observe:


In [55]:
x2_sub[0, 0] = 100
print(x2_sub)

[[100   5]
 [  7   6]]


In [56]:
print(x2)

[[100   5   2   4]
 [  7   6   8   8]
 [  1   6   7   7]]


This default behaviour is actually useful:it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

**1. 浅拷贝（Shallow Copy）:**

浅拷贝创建一个新对象，但只复制原始对象中的引用。这意味着如果原始对象中有嵌套对象（例如列表、字典等），新对象和原始对象将共享这些嵌套对象。因此，如果浅拷贝的对象修改了嵌套对象，原始对象也会受到影响。
例如：

```python
import copy

original_list = [1, 2, 3, [4, 5]]

shallow_copy = copy.copy(original_list)

shallow_copy[3][0] = 99

print(original_list)  # 输出: [1, 2, 3, [99, 5]]
print(shallow_copy)  # 输出: [1, 2, 3, [99, 5]]
```

上述示例中，将 `shallow_copy` 中的嵌套列表 `[4, 5]` 的第一个元素改成 `99`，原始列表 `original_list` 也受到了影响。

**2. 深拷贝（Deep Copy）：**

与浅拷贝不同，深拷贝会递归地复制对象的所有元素，包括嵌套对象。这意味着新对象与原始对象完全独立，它们没有共享内部对象。当您修改深拷贝后的对象时，原始对象不受影响。
例如：

```python
import copy

original_list = [1, 2, 3, [4, 5]]

deep_copy = copy.deepcopy(original_list)

deep_copy[3][0] = 99

print(original_list)  # 输出: [1, 2, 3, [4, 5]]
print(deep_copy)  # 输出: [1, 2, 3, [99, 5]]
```

在这个示例中，将 `deep_copy` 中的嵌套列表 `[4, 5]` 的第一个元素改成 `99`，但原始列表 `original_list` 保持不变。

**总结一下，浅拷贝仅复制对象的引用，而深拷贝创建对象的完全独立副本**


# Reshaping of Arrays
`reshape` method

In [58]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

! the size of the initial array must match the size of the reshape array.
the `reshape` method will use a no-copy view of the initial array, but with
non-contiguous memory buffers this is not always the case.

`newaxis`: conversion of a one-dimensional array into a two-dimensional row or column matrix.

In [60]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [61]:
# row vector via reshape
x.reshape(1, 3)

array([[1, 2, 3]])

In [62]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [63]:
# column vector via reshape
x.reshape(3, 1)

array([[1],
       [2],
       [3]])

In [64]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

# Array Concatenation and Splitting

## Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routine 
`np.concatenate`, `np.vstack`, `np.hstack`.
`np.concatenate` takes a tuple or list of arrays as its first argument:


In [65]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [66]:
z = [99, 99, 99]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [68]:
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [70]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

这段代码演示了使用 `numpy` 库的 `concatenate` 函数如何将数组相互连接。了解此示例的关键是 `concatenate` 函数的功能以及函数的 `axis` 参数。

**`np.concatenate`:**
`np.concatenate` 函数用于将两个或多个数组沿特定轴连接，即将它们堆叠在一起。传递给 `concatenate` 的参数应为数组的列表或元组，这些数组会按照指定的轴进行拼接。

**`axis` 参数:**
`axis` 参数决定了连接操作沿哪个维度进行。`axis=0` (默认值) 表示沿第一个维度（行）连接数组，`axis=1` 表示沿第二个维度（列）连接数组。

现在让我们详细了解两个示例：

1. `np.concatenate([grid, grid])`：
由于默认的 `axis` 参数值为 0，所以这个操作将沿第一个维度（即行）连接数组。可以将其视为在垂直方向上堆叠两个相同的 `grid` 数组。结果数组看起来像这样：

```
[[1, 2, 3],
[4, 5, 6],
[1, 2, 3],
[4, 5, 6]]
```

2. `np.concatenate([grid, grid], axis=1)`：
在这个例子中，我们通过将 `axis` 参数设置为 1，将两个数组沿第二个维度（即列）连接起来。可以将其视为在水平方向上堆叠两个相同的 `grid` 数组。结果数组看起来像这样：

```
[[1, 2, 3, 1, 2, 3],
[4, 5, 6, 4, 5, 6]]
```

要记住的是，根据不同的 `axis` 参数值，`concatenate` 函数可以在垂直方向上（沿行）或水平方向上（沿列）拼接数组。